# Generated by Django 5.1.1 on 2024-09-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_healthtask_user_alter_anomaly_video_taskinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecommendation',
            old_name='health_record',
            new_name='health_disease',
        ),
        migrations.RenameField(
            model_name='healthrecord',
            old_name='health_conditions',
            new_name='health_disease',
        ),
    ]
