# Generated by Django 5.1.1 on 2024-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_rename_health_record_healthrecommendation_health_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='health_disease',
            field=models.CharField(max_length=100),
        ),
    ]
