# Generated by Django 5.1.1 on 2024-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_healthrecommendation_health_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecommendation',
            name='health_disease',
            field=models.CharField(max_length=255),
        ),
    ]
